[2025-06-09T08:21:47.998+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T08:21:48.074+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NetSuite_Daily_ToWarehouse_F99.Download_And_Upsert_F99 manual__2025-06-09T08:21:45.301486+00:00 [queued]>
[2025-06-09T08:21:48.094+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NetSuite_Daily_ToWarehouse_F99.Download_And_Upsert_F99 manual__2025-06-09T08:21:45.301486+00:00 [queued]>
[2025-06-09T08:21:48.094+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-09T08:21:48.121+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Download_And_Upsert_F99> on 2025-06-09 08:21:45.301486+00:00
[2025-06-09T08:21:48.130+0000] {standard_task_runner.py:63} INFO - Started process 33 to run task
[2025-06-09T08:21:48.133+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NetSuite_Daily_ToWarehouse_F99', 'Download_And_Upsert_F99', 'manual__2025-06-09T08:21:45.301486+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/dag_netsuite.py', '--cfg-path', '/tmp/tmppyhoaedf']
[2025-06-09T08:21:48.137+0000] {standard_task_runner.py:91} INFO - Job 376: Subtask Download_And_Upsert_F99
[2025-06-09T08:21:48.218+0000] {task_command.py:426} INFO - Running <TaskInstance: NetSuite_Daily_ToWarehouse_F99.Download_And_Upsert_F99 manual__2025-06-09T08:21:45.301486+00:00 [running]> on host cfb67c7eb5e0
[2025-06-09T08:21:48.310+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='NetSuite_Daily_ToWarehouse_F99' AIRFLOW_CTX_TASK_ID='Download_And_Upsert_F99' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T08:21:45.301486+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T08:21:45.301486+00:00'
[2025-06-09T08:21:48.311+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T08:22:46.137+0000] {logging_mixin.py:188} INFO - [F99] Preview nội dung: Type,Period,Date,Document Number,Status,Người đề nghị thanh toán,Tara - Approver LV 1,Tara - Approver LV 2,Tara - DNTT Approval Status,TARA - Approval Status,KMP,Memo,Tara _Document_Link,Transaction Type Detail
Invoice,Dec 2021,31/12/2021,OB21-INV-0042,Paid In Full,,,,,,"6408000 - Các khoản chiết kh
[2025-06-09T08:22:50.105+0000] {logging_mixin.py:188} INFO - [F99] Số dòng đọc được: 384979
[2025-06-09T08:22:50.876+0000] {warnings.py:110} WARNING - /opt/***/plugins/Project/TaraFunction.py:224: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df.to_sql(tablename.replace('"','').split('.')[1],

[2025-06-09T08:22:50.947+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T08:22:50.953+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_netsuite.py", line 47, in download_and_upsert_F99
    upsert_data2datalake(df=df, tablename='"NetSuite"."F99_CustomSearch_4532"', primary_key='filename')
  File "/opt/airflow/plugins/Project/TaraFunction.py", line 224, in upsert_data2datalake
    df.to_sql(tablename.replace('"','').split('.')[1],
  File "/usr/local/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/core/generic.py", line 3106, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/sql.py", line 844, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/sql.py", line 2840, in to_sql
    table.create()
  File "/usr/local/lib/python3.11/site-packages/pandas/io/sql.py", line 986, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/sql.py", line 972, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/sql.py", line 2855, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/sql.py", line 2662, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Connection' object has no attribute 'cursor'
[2025-06-09T08:22:51.015+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=NetSuite_Daily_ToWarehouse_F99, task_id=Download_And_Upsert_F99, run_id=manual__2025-06-09T08:21:45.301486+00:00, execution_date=20250609T082145, start_date=20250609T082148, end_date=20250609T082251
[2025-06-09T08:22:51.053+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 376 for task Download_And_Upsert_F99 ('Connection' object has no attribute 'cursor'; 33)
[2025-06-09T08:22:51.098+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-09T08:22:51.130+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T08:22:51.133+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
