[2025-06-04T10:15:52.113+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-04T10:15:52.138+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: excel_to_postgres_test_data_dag.load_excel_data_to_postgres manual__2025-06-04T10:15:49.624308+00:00 [queued]>
[2025-06-04T10:15:52.156+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: excel_to_postgres_test_data_dag.load_excel_data_to_postgres manual__2025-06-04T10:15:49.624308+00:00 [queued]>
[2025-06-04T10:15:52.157+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-04T10:15:52.174+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_excel_data_to_postgres> on 2025-06-04 10:15:49.624308+00:00
[2025-06-04T10:15:52.180+0000] {standard_task_runner.py:63} INFO - Started process 62 to run task
[2025-06-04T10:15:52.182+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'excel_to_postgres_test_data_dag', 'load_excel_data_to_postgres', 'manual__2025-06-04T10:15:49.624308+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_postgres_test_data_dag.py', '--cfg-path', '/tmp/tmptfgg76aa']
[2025-06-04T10:15:52.185+0000] {standard_task_runner.py:91} INFO - Job 148: Subtask load_excel_data_to_postgres
[2025-06-04T10:15:52.234+0000] {task_command.py:426} INFO - Running <TaskInstance: excel_to_postgres_test_data_dag.load_excel_data_to_postgres manual__2025-06-04T10:15:49.624308+00:00 [running]> on host 8b60c3c987d2
[2025-06-04T10:15:52.313+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='excel_to_postgres_test_data_dag' AIRFLOW_CTX_TASK_ID='load_excel_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T10:15:49.624308+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T10:15:49.624308+00:00'
[2025-06-04T10:15:52.314+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-04T10:15:52.328+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-04T10:15:52.328+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/excel_to_postgres_test_data_dag.py", line 40, in load_excel_to_postgres
    df = pd.read_excel(EXCEL_FILE_PATH)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1550, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1402, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\TranHuuHau\\airflow-docker\\excel\\all_tara_backup.xlsx'
[2025-06-04T10:15:52.339+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=excel_to_postgres_test_data_dag, task_id=load_excel_data_to_postgres, run_id=manual__2025-06-04T10:15:49.624308+00:00, execution_date=20250604T101549, start_date=20250604T101552, end_date=20250604T101552
[2025-06-04T10:15:52.350+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 148 for task load_excel_data_to_postgres ([Errno 2] No such file or directory: 'D:\\TranHuuHau\\airflow-docker\\excel\\all_tara_backup.xlsx'; 62)
[2025-06-04T10:15:52.358+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-04T10:15:52.374+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-04T10:15:52.375+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
