[2025-06-09T09:23:43.984+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T09:23:44.020+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NetSuite_Daily_ToWarehouse_F99.Download_And_Upsert_F99 manual__2025-06-09T09:22:18.161530+00:00 [queued]>
[2025-06-09T09:23:44.030+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NetSuite_Daily_ToWarehouse_F99.Download_And_Upsert_F99 manual__2025-06-09T09:22:18.161530+00:00 [queued]>
[2025-06-09T09:23:44.031+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-09T09:23:44.047+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Download_And_Upsert_F99> on 2025-06-09 09:22:18.161530+00:00
[2025-06-09T09:23:44.052+0000] {standard_task_runner.py:63} INFO - Started process 49 to run task
[2025-06-09T09:23:44.057+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NetSuite_Daily_ToWarehouse_F99', 'Download_And_Upsert_F99', 'manual__2025-06-09T09:22:18.161530+00:00', '--job-id', '385', '--raw', '--subdir', 'DAGS_FOLDER/dag_netsuite.py', '--cfg-path', '/tmp/tmpx_fq9qar']
[2025-06-09T09:23:44.060+0000] {standard_task_runner.py:91} INFO - Job 385: Subtask Download_And_Upsert_F99
[2025-06-09T09:23:44.113+0000] {task_command.py:426} INFO - Running <TaskInstance: NetSuite_Daily_ToWarehouse_F99.Download_And_Upsert_F99 manual__2025-06-09T09:22:18.161530+00:00 [running]> on host 87d36d91b2b5
[2025-06-09T09:23:44.199+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='NetSuite_Daily_ToWarehouse_F99' AIRFLOW_CTX_TASK_ID='Download_And_Upsert_F99' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T09:22:18.161530+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T09:22:18.161530+00:00'
[2025-06-09T09:23:44.201+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T09:24:13.268+0000] {logging_mixin.py:188} INFO - [F99] Preview nội dung: Type,Period,Date,Document Number,Status,Người đề nghị thanh toán,Tara - Approver LV 1,Tara - Approver LV 2,Tara - DNTT Approval Status,TARA - Approval Status,KMP,Memo,Tara _Document_Link,Transaction Type Detail
Invoice,Dec 2021,31/12/2021,OB21-INV-0042,Paid In Full,,,,,,"6408000 - Các khoản chiết kh
[2025-06-09T09:24:16.925+0000] {logging_mixin.py:188} INFO - [F99] Số dòng đọc được: 385001
[2025-06-09T09:24:17.586+0000] {logging_mixin.py:188} INFO - [Datalake] Lỗi xóa dữ liệu cũ: relation "NetSuite.F99_CustomSearch_4532" does not exist
LINE 1: DELETE FROM "NetSuite"."F99_CustomSearch_4532" WHERE "filena...
                    ^
[2025-06-09T09:25:05.221+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T09:25:05.270+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/Project/TaraFunction.py", line 267, in upsert_data2datalake
    cur.execute(insert_sql)
psycopg2.errors.UndefinedTable: relation "NetSuite.F99_CustomSearch_4532" does not exist
LINE 1: INSERT INTO "NetSuite"."F99_CustomSearch_4532" ("Invoice","F...
                    ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_netsuite.py", line 47, in download_and_upsert_F99
    upsert_data2datalake(df=df, tablename='"NetSuite"."F99_CustomSearch_4532"', primary_key='filename')
  File "/opt/airflow/plugins/Project/TaraFunction.py", line 274, in upsert_data2datalake
    raise Exception(f"[Datalake] Ghi dữ liệu thất bại: {e}")
Exception: [Datalake] Ghi dữ liệu thất bại: relation "NetSuite.F99_CustomSearch_4532" does not exist
LINE 1: INSERT INTO "NetSuite"."F99_CustomSearch_4532" ("Invoice","F...
                    ^

[2025-06-09T09:25:05.448+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=NetSuite_Daily_ToWarehouse_F99, task_id=Download_And_Upsert_F99, run_id=manual__2025-06-09T09:22:18.161530+00:00, execution_date=20250609T092218, start_date=20250609T092344, end_date=20250609T092505
[2025-06-09T09:25:05.539+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 385 for task Download_And_Upsert_F99 ([Datalake] Ghi dữ liệu thất bại: relation "NetSuite.F99_CustomSearch_4532" does not exist
LINE 1: INSERT INTO "NetSuite"."F99_CustomSearch_4532" ("Invoice","F...
                    ^
; 49)
[2025-06-09T09:25:05.727+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-09T09:25:05.843+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T09:25:05.847+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
