[2025-06-09T03:43:36.196+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T03:43:36.220+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NetSuite_Invoice_Daily_Extractor.fetch_netsuite_invoice scheduled__2025-06-07T20:00:00+00:00 [queued]>
[2025-06-09T03:43:36.229+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NetSuite_Invoice_Daily_Extractor.fetch_netsuite_invoice scheduled__2025-06-07T20:00:00+00:00 [queued]>
[2025-06-09T03:43:36.229+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-09T03:43:36.244+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_netsuite_invoice> on 2025-06-07 20:00:00+00:00
[2025-06-09T03:43:36.250+0000] {standard_task_runner.py:63} INFO - Started process 42 to run task
[2025-06-09T03:43:36.253+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NetSuite_Invoice_Daily_Extractor', 'fetch_netsuite_invoice', 'scheduled__2025-06-07T20:00:00+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/crawl_netsuite.py', '--cfg-path', '/tmp/tmp9w45p9ki']
[2025-06-09T03:43:36.258+0000] {standard_task_runner.py:91} INFO - Job 190: Subtask fetch_netsuite_invoice
[2025-06-09T03:43:36.347+0000] {task_command.py:426} INFO - Running <TaskInstance: NetSuite_Invoice_Daily_Extractor.fetch_netsuite_invoice scheduled__2025-06-07T20:00:00+00:00 [running]> on host 6b5241449da9
[2025-06-09T03:43:36.449+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='NetSuite_Invoice_Daily_Extractor' AIRFLOW_CTX_TASK_ID='fetch_netsuite_invoice' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-07T20:00:00+00:00'
[2025-06-09T03:43:36.454+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T03:43:38.367+0000] {logging_mixin.py:188} INFO - ✅ Đăng nhập thành công.
[2025-06-09T03:43:39.027+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T03:43:39.028+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawl_netsuite.py", line 41, in fetch_invoice_data
    df = pd.read_csv(StringIO(response_csv.text))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas/_libs/parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 12, saw 2

[2025-06-09T03:43:39.045+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=NetSuite_Invoice_Daily_Extractor, task_id=fetch_netsuite_invoice, run_id=scheduled__2025-06-07T20:00:00+00:00, execution_date=20250607T200000, start_date=20250609T034336, end_date=20250609T034339
[2025-06-09T03:43:39.061+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 190 for task fetch_netsuite_invoice (Error tokenizing data. C error: Expected 1 fields in line 12, saw 2
; 42)
[2025-06-09T03:43:39.079+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-09T03:43:39.115+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T03:43:39.120+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
