{"timestamp":"2025-06-04T04:33:10.998167","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-06-04T04:33:10.998862","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/test_postgres_conn.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-06-04T04:33:12.356526Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-04T04:33:12.356875Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-04T04:33:12.357452Z","level":"info","event":"Current task name:test_postgres_connection","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-04T04:33:12.357698Z","level":"info","event":"Dag name:test_postgres_connection_dag","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-04T04:33:11.220553","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-06-04T04:33:12.356974","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowNotFoundException","exc_value":"The conn_id `datawarehouse_postgres` isn't defined","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":838,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1130,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/test_postgres_conn.py","lineno":9,"name":"test_postgres_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py","lineno":149,"name":"get_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":248,"name":"connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py","lineno":64,"name":"get_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py","lineno":482,"name":"get_connection_from_secrets"}]},{"exc_type":"AirflowRuntimeError","exc_value":"CONNECTION_NOT_FOUND: {'conn_id': 'datawarehouse_postgres'}","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py","lineno":472,"name":"get_connection_from_secrets"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py","lineno":142,"name":"get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/context.py","lineno":161,"name":"_get_connection"}]}]}
{"timestamp":"2025-06-04T04:33:12.358748Z","level":"info","event":"❌ Kết nối thất bại: The conn_id `datawarehouse_postgres` isn't defined","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-04T04:33:12.358997Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-04T04:33:12.359201Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-04T04:33:12.359470Z","level":"info","event":"Task:<Task(PythonOperator): test_postgres_connection>","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-04T04:33:12.359719Z","level":"info","event":"Failure caused by The conn_id `datawarehouse_postgres` isn't defined","chan":"stdout","logger":"task"}
